language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - dev

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=1

before_install:
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - phpcs --standard=phpcs.xml $(find . -name '*.php')
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
